### ISSUE TITLE
won't work with dvd.netflix.com

### ISSUE THREAD

**Issue by metta1** [m5n/netflix-ratings-extractor#6]
Great concept, wish it worked for my 3,000 ratings, now that Netflix is doing away with its rating system, going to thumbs up/down.

When I press the Start button on the MoviesYouveSeen page, I get the following output:
ID	Title	Rating	Date
Done.
Extracted 0 ratings in 1 seconds.

This happens in both Firefox and Chrome. Is this because Netflix has implemented NEXT button on each page instead of a continuous scroll? Any fix planned? I'd contribute to have something written before 15 years of ratings are lost (and I bet I'm not the only one.)

**Comment by m5n** [comment]
Thanks for letting me know, (and for the hint). I'll take a look at this hopefully this week.

**Comment by m5n** [comment]
It worked for me* on https://www.netflix.com/MoviesYouveSeen; are you able to load that page or does it redirect to dvd.netflix.com?

* It does not handle thumbs up/down ratings right, that'll need to be fixed.

**Comment by m5n** [comment]
I fixed the up/down rating issue. The current version 2.2 of the script has this fix.

**Comment by metta1** [comment]
Thank you! This seems to work  the way it's intended for my Netflix streaming account, but not for dvd.netflix.com which is where I have nearly all of my ratings (they are not associated with each other.) The address you provided goes  to
https://dvd.netflix.com/MemberHome
when I'm logged in in another tab in Firefox 53.0. Using Windows 7 desktop

There is a page
https://dvd.netflix.com/MoviesYouveSeen but it does have the next button.

**Comment by m5n** [comment]
For the page that has the Next button, you can try an older version of the script: https://raw.githubusercontent.com/m5n/netflix-ratings-extractor/10e33f0063aee2b26f03c12ea3acf5dc2d94b3fe/netflix-ratings-extractor.user.js

That one has support for the next buttons but the UI it expects may be outdated enough that the script won't run. Does the DVD plan ratings page look the same as the streaming plan ratings page?

I only have the streaming plan, so unfortunately I cannot test the DVD plan page.  If you're comfortable with potentially sharing personal data, you could send me the source of the DVD plan ratings page. From there I can figure out where the ratings data is located on the page and how to programmatically click the Next button. I'd ask you to test the updated script once it's ready to see if it works. My email is [EMAIL REMOVED] (Feel free to remove account info and replace movie info with fake data, just leave the HTML tags in tact.)

**Comment by m5n** [comment]
Oops, didn't mean to close this.

**Comment by metta1** [comment]
I thank you for your help on this. I retried the older script and the original problem was replicated:
No ratings extracted

ID	Title	Rating	Date
Done.
Extracted 0 ratings in 1 seconds.

I have recently learned that dvd.netflix.com will be keeping its original rating system (5 stars), unlike its streaming counterpart, so I'm content with that for now.

Thanks again for your assistance.

**Comment by m5n** [comment]
No problem!
